version: "3"

services:
  server:
    container_name: SJIRun_Server
    build: server/

    environment:
      PORT: 80

      APP_TITLE: ${APP_TITLE}

      CLIENT_URL: ${CLIENT_URL}
      SERVER_URL: ${SERVER_URL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}

      MONGO_PREFIX: ${MONGO_PREFIX}
      MONGO_URL: ${MONGO_URL}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}

      ADMIN_EMAILS: ${ADMIN_EMAILS}

    # Port syntax is as follows: (exposed port):(container)
    # Exposed syntax is as follows: (container)
    expose:
      - 80

  client:
    container_name: SJIRun_Client
    build:
      context: client/
      args:
        APP_TITLE: ${APP_TITLE}
        CLIENT_URL: ${CLIENT_URL}
        SERVER_URL: ${SERVER_URL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}

    environment:
      PORT: 80 # Doesn't do anything, yet

    # Port syntax is as follows: (exposed port):(container)
    # Exposed syntax is as follows: (container)
    expose:
      - 80

    # 'client' service should wait until the 'server' service is ready.
    depends_on:
      - server
