# Sample docker-compose override, you can use this to configure your networks, open ports, etc.

version: "3"

services:
  server:
    networks:
      - web_default

  client:
    networks:
      - web_default

networks:
  web_default:
    external: true